fix acpacity expansion IT
thulab/IginX pull request #429
Opened 2022-10-28 05:56 UTC by RemHero

2022-11-04 08:37 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/IoTDBHistoryDataCapacityExpansionIT.java
> +        session.executeSql("ADD STORAGEENGINE (\"127.0.0.1\", 6668, \"" + ENGINE_TYPE + "\", \"username:root, password:root, sessionPoolSize:20, has_data:no, is_read_only:true\");");
Are you sure here "hasdata:no" is correct?

2022-11-04 08:50 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/scaleout/IoTDBRestfulScaleOutIT.java
>  package cn.edu.tsinghua.iginx.integration.scaleout;
IoTDBRestfulScaleOutIT seems to have so similar functionality as IoTDBSqlScaleOutIt and IoTDBTagScaleOutIT. But why do they differ so much in their respective testing process and implementation?
Why not make a better abstraction for them to clear up the code?

2022-11-04 09:07 UTC, zhuyuqing commented on .github/workflows/scale-out.yml
>    IoTDB-Tag-Test:
Tag-Test seems to have similar testing objectives as session test ad rest test in the same file. So why not structure them similarly?

2022-11-04 09:07 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/rest/RestIT.java
> +        SessionExecuteSqlResult res = session.executeSql("show time series");
Can these session commands be implemented as REST commands?

2022-11-04 09:08 UTC, zhuyuqing requested changes
@RemHero Would you please update the structure of scaleout tests to let similar tests have similar structure? Thanks.

2022-11-09 01:28 UTC, SolomonAnn commented
Remove useless files, including `.github/actions/iginxRunner/iginxLog.txt`, `.github/actions/iotdbRunner/iotdb1Log.txt` and `.github/actions/iotdbRunner/iotdb2Log.txt`.

2022-11-09 01:32 UTC, SolomonAnn commented on .github/actions/iginxRunner/action.yml
> +#        chmod +x "${GITHUB_WORKSPACE}/core/target/iginx-core-${{inputs.version}}/sbin/start_iginx.sh"
Delete unused lines.

2022-11-10 15:41 UTC, SolomonAnn approved these changes

2022-11-11 01:08 UTC, zhuyuqing approved these changes

2022-11-11 01:08 UTC, merged