sync protocol
thulab/IginX pull request #444
Opened 2022-11-16 15:39 UTC by iznauy

2022-11-17 01:47 UTC, zhuyuqing requested changes
Please provide an adequate description on the functionality of the PR.

2022-11-17 01:52 UTC, zhuyuqing submitted a review, later dismissed
Please fix accordingly.

2022-11-17 01:52 UTC, zhuyuqing commented on sync/src/main/java/cn/edu/tsinghua/iginx/protocol/SyncProtocol.java
> +
Please add adequate comments and descriptions on the interface.

2022-11-17 01:52 UTC, zhuyuqing commented on sync/src/main/java/cn/edu/tsinghua/iginx/proposal/ProposalListener.java
> +
Please add definition descriptions on the interface.

2022-11-17 01:52 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/JsonUtils.java
> +
Why use a Json parser different from that used in other modules?
Consider changes.

2022-11-22 00:57 UTC, zhanglingzhe0820 approved these changes

2022-11-23 01:02 UTC, merged