add the schema prefix option when user add storage engine for iotdb
thulab/IginX pull request #445
Opened 2022-11-17 07:28 UTC by RemHero

add the schema prefix option when user add storage engine for iotdb

2022-11-18 07:57 UTC, Cauchy-NY commented on core/src/main/java/cn/edu/tsinghua/iginx/metadata/entity/TimeSeriesInterval.java
> +    private String timeSeriesPrefix = null;
感觉会引起误解

2022-11-18 08:07 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> +                if (index < schemaPrefix.size() && schemaPrefix.get(index) != null) //set the virtual schema prefix
如果，用户给的命令是，add storage engine，isReadOnly=false，后续如果再发生重分片，这个前缀是如何确保被继承呢？
代码好像并没有涉及这一点？

2022-11-18 08:07 UTC, zhuyuqing requested changes

2022-11-18 08:07 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> +                if (index < schemaPrefix.size() && schemaPrefix.get(index) != null) //set the virtual schema prefix
@iznauy 你觉得呢？

2022-11-19 06:47 UTC, zhuyuqing commented on dataSources/iotdb11/src/main/java/cn/edu/tsinghua/iginx/iotdb/IoTDBStorage.java
>  import cn.edu.tsinghua.iginx.engine.physical.task.StoragePhysicalTask;
InfluxDB接口没有相应地修改？

2022-11-19 06:47 UTC, zhuyuqing requested changes

2022-11-19 06:47 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/iotdb/IoTDBHistoryDataCapacityExpansionIT.java
>          testWriteAndQueryAfterCapacityExpansion_oriNoDataExpNoData();
InfluxDB的测试也加一下？

2022-11-21 01:06 UTC, zhuyuqing commented on core/src/main/java/cn/edu/tsinghua/iginx/IginxWorker.java
> +                if (index < schemaPrefix.size() && schemaPrefix.get(index) != null) //set the virtual schema prefix
后续写入数据位置，看起来是，取决于分片策略；写入数据前缀，取决于用户写入声明

2022-11-22 00:52 UTC, iznauy approved these changes

2022-11-22 00:53 UTC, iznauy approved these changes

2022-11-24 01:31 UTC, zhuyuqing commented on test/src/test/java/cn/edu/tsinghua/iginx/integration/expansion/influxdb/InfluxDBHistoryDataGeneratorTest.java
> +//        tags.put("host", "2");
为何减少测试写入的数据内容？

2022-11-30 01:49 UTC, zhuyuqing approved these changes

2022-11-30 08:26 UTC, iznauy approved these changes

2022-11-30 08:26 UTC, merged