optimize the string type timePrecision to enum type
thulab/IginX pull request #475
Opened 2022-12-08 13:02 UTC by RemHero

optimize the “string” type timePrecision to “enum” type

2022-12-09 01:57 UTC, zhuyuqing commented on shared/src/main/java/cn/edu/tsinghua/iginx/utils/TimeUtils.java
>              default:
You have defined TimePrecision to be an Enum with precisions like day, week, year. But, here, you do not have processing logic for those precisions and by default you set it to nanosecond. This is an obvious bug.

2022-12-09 01:58 UTC, zhuyuqing requested changes
Would you please move example and IT code from PR#465 to this PR to make it complete? Thanks.

2022-12-12 02:19 UTC, zhuyuqing requested changes
Why not check all related spots suspicious of bugs?

2022-12-14 01:04 UTC, iznauy approved these changes

2022-12-14 01:05 UTC, Cauchy-NY approved these changes

2022-12-15 01:08 UTC, zhuyuqing approved these changes

2022-12-15 01:09 UTC, merged